### ISSUE TITLE
depends HTTP Error 404

### ISSUE THREAD

**Issue by fengdasuk19** [lotem/rime-gits#22]
执行 `download_depends.py`，有如下提示：

```
Traceback (most recent call last):
  File "download_depends.py", line 63, in <module>
    download_and_extract(entry['url'], entry['dest'])
  File "download_depends.py", line 21, in download_and_extract
    f = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

```

然后尝试在浏览器中输入该脚本中 `FILE_LIST` 的各项 URL，发现下述 URL 已经失效（404）：

```
https://protobuf.googlecode.com/files/protoc-2.5.0-win32.zip
https://protobuf.googlecode.com/files/protobuf-2.5.0.zip
https://googletest.googlecode.com/files/gtest-1.7.0.zip
http://zlib.net/zlib-1.2.8.tar.gz
```

也就是说只有[最后一个 URL](http://jaist.dl.sourceforge.net/project/wtl/WTL%208.0/WTL%208.0%20Final/WTL80_7161_Final.zip) 还可用。

**Comment by Prcuvu** [comment]
以下列地址替换：
```
https://github.com/google/protobuf/releases/download/v2.5.0/protoc-2.5.0-win32.zip
https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.zip
https://github.com/google/googletest/archive/release-1.7.0.zip
http://www.zlib.net/fossils/zlib-1.2.8.tar.gz
```

**Comment by fengdasuk19** [comment]
感谢 @Prcuvu ，新提供的地址是可用的。

**Comment by huanxiu** [comment]
反饋，將鏈接全部替換後，在Python 2.7.14的環境下運行，不掛ss和掛了ss均顯示500錯誤，換開l藍燈後成功
